### ISSUE TITLE
password other than admin is not possible

### ISSUE THREAD

**Issue by mdhatx73** [weggetor/ioBroker.airconwithme#92]
I tried several passwords, but I only got it working with admin/admin. Is ther a was changing the default password?

node -v
v14.18.3

Error message in Logfile
Login fehlgeschlagen !

I also tried different passwords with different length / with and without special characters.

**Comment by weggetor** [comment]
Stupid question: Did you change the password on the Intesis Webpage also ?

**Comment by mdhatx73** [comment]
> Stupid question: Did you change the password on the Intesis Webpage also ?

I changed it on the local webpage on the MH-AC-WIFI-1 adapter and also in the iobroker config - tried different passwords - so also I tried simple passwords like r2d2c3po without special characters. Is there a limitation in length?
admin / admin works.

**Comment by weggetor** [comment]
OK, you were absolutely right! I hardcoded admin/admin into the adapter instead of using the settings - shame on me!
I made a new version 0.0.4 today that fixes the problem. Cant't see it at the moment in latest - maybe it is updated tomorrow... If it is very urgent you can install it from npm or wait some time until it is shown in IOBroker
